### ISSUE TITLE
TypeError: Class advice impossible in Python3.  Use the @implementer class decorator instead.

### ISSUE THREAD

**Issue by tnhgiang** [ceshine/yt8m-2019#2]
Thank you for sharing your awesome work.

I got a problem when running `bash scripts/pretraining.bash`
![Screenshot from 2019-11-08 13-27-35](https://user-images.githubusercontent.com/45427365/68454555-9717f380-022b-11ea-93e7-c2b0ebbef8b5.png)

**Comment by ceshine** [comment]
That seems to be related to [this issue for Apex](https://github.com/NVIDIA/apex/issues/116). Please take a look and see if the solution there works for you. Or just remove Apex. Apex is completely optional for this project.

BTW, I have built docker image available at [ceshine/yt8m-2019](https://hub.docker.com/r/ceshine/yt8m-2019).
