### ISSUE TITLE
Tensor reshape error using docker image

### ISSUE THREAD

**Issue by RasmusRavnFrost** [ceshine/yt8m-2019#3]
I tried training using the public docker image without any modifications but when I try to run ```bash scripts/pretraining.bash´´´ I get the following error.
I believe it could be a version compatability problem with tensorflow but I will let you know after some tests. Can you give me a conda list output of your docker image for me to compare?

Offset: 0
Offset: 0
SampleFrameModelWrapper(
  (model): GatedDBoFModel(
    (pooler): AvgMaxPooler()
    (encoder): Sequential(
      (0): Linear(in_features=1152, out_features=4096, bias=True)
      (1): ReLU()
      (2): TransposeLayer()
      (3): BNSE1dModule(
        (bn1): BatchNorm1d(4096, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (fc1): Conv1d(4096, 512, kernel_size=(1,), stride=(1,))
        (relu): ReLU()
        (bn2): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (fc2): Conv1d(512, 4096, kernel_size=(1,), stride=(1,))
        (sigmoid): Sigmoid()
      )
    )
    (intermediate_fc): Sequential(
      (0): BatchNorm1d(8192, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (1): Dropout(p=0.5, inplace=False)
      (2): Linear(in_features=8192, out_features=2048, bias=False)
      (3): ReLU()
      (4): BNSEModule(
        (bn1): BatchNorm1d(2048, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (fc1): Linear(in_features=2048, out_features=512, bias=True)
        (relu): ReLU()
        (bn2): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (fc2): Linear(in_features=512, out_features=2048, bias=True)
        (sigmoid): Sigmoid()
      )
    )
    (expert_fc): Sequential(
      (0): BatchNorm1d(2048, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (1): Dropout(p=0.5, inplace=False)
      (2): Linear(in_features=2048, out_features=4000, bias=True)
    )
    (gating_fc): Sequential(
      (0): BatchNorm1d(2048, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (1): Dropout(p=0.5, inplace=False)
      (2): Linear(in_features=2048, out_features=5, bias=True)
    )
  )
)
[INFO][03/06/2020 12:33:51] SEED: 4827
[INFO][03/06/2020 12:33:51] # of parameters: 36,043,685
[INFO][03/06/2020 12:33:51] # of trainable parameters: 36,043,685
[INFO][03/06/2020 12:33:51] Optimizer Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    eps: 1e-06
    initial_lr: 0.0003
    lr: 0.0002999962874535931
    weight_decay: 0

Parameter Group 1
    amsgrad: False
    betas: (0.9, 0.999)
    eps: 1e-06
    initial_lr: 0.0003
    lr: 0.0002999962874535931
    weight_decay: 0
)
[INFO][03/06/2020 12:33:51] ====================Epoch 1====================
Traceback (most recent call last):
  File "/opt/conda/envs/yt8m/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/envs/yt8m/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/docker/src/yt8m/train_video.py", line 274, in <module>
    main()
  File "/home/docker/src/yt8m/train_video.py", line 265, in main
    train_loader, valid_loader)
  File "/home/docker/src/yt8m/train_video.py", line 182, in train_from_start
    total_steps=n_steps, checkpoint_interval=config['ckpt_interval']
  File "/opt/conda/envs/yt8m/lib/python3.7/site-packages/helperbot/bot.py", line 168, in train
    input_tensors, targets)
  File "/opt/conda/envs/yt8m/lib/python3.7/site-packages/helperbot/bot.py", line 82, in train_one_step
    output = self.model(*input_tensors)
  File "/opt/conda/envs/yt8m/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/docker/src/yt8m/models.py", line 34, in forward
    return self.model(features, masks)
  File "/opt/conda/envs/yt8m/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/docker/src/yt8m/models.py", line 152, in forward
    encoded = self.encoder(tensor)
  File "/opt/conda/envs/yt8m/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/envs/yt8m/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/opt/conda/envs/yt8m/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/envs/yt8m/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/opt/conda/envs/yt8m/lib/python3.7/site-packages/torch/nn/functional.py", line 1372, in linear
    output = input.matmul(weight.t())
RuntimeError: cannot reshape tensor of 0 elements into shape [-1, 0] because the unspecified dimension size -1 can be any value and is ambiguous
mv: missing destination file operand after 'data/cache/video/dbof-3'
Try 'mv --help' for more information.
Offset: 0
Offset: 0
SampleFrameModelWrapper(
  (model): NeXtVLADModel(
    (video_encoder): NeXtVLAD(
      (cluster_dropout): Dropout2d(p=0.25, inplace=False)
      (expansion_mapper): Linear(in_features=1024, out_features=2048, bias=True)
      (soft_assignment_mapper): Sequential(
        (0): Linear(in_features=2048, out_features=1024, bias=False)
        (1): TimeFirstBatchNorm1d(
          (bn): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        )
      )
      (attention_mapper): Linear(in_features=2048, out_features=16, bias=True)
      (final_bn): BatchNorm1d(8192, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (audio_encoder): NeXtVLAD(
      (cluster_dropout): Dropout2d(p=0.25, inplace=False)
      (expansion_mapper): Linear(in_features=128, out_features=256, bias=True)
      (soft_assignment_mapper): Sequential(
        (0): Linear(in_features=256, out_features=512, bias=False)
        (1): TimeFirstBatchNorm1d(
          (bn): BatchNorm1d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        )
      )
      (attention_mapper): Linear(in_features=256, out_features=16, bias=True)
      (final_bn): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (intermediate_fc): Sequential(
      (0): Linear(in_features=8704, out_features=2048, bias=True)
      (1): ReLU()
    )
    (se_gating): BNSEModule(
      (bn1): BatchNorm1d(2048, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (fc1): Linear(in_features=2048, out_features=512, bias=True)
      (relu): ReLU()
      (bn2): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (fc2): Linear(in_features=512, out_features=2048, bias=True)
      (sigmoid): Sigmoid()
    )
    (expert_fc): Sequential(
      (0): BatchNorm1d(2048, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (1): Dropout(p=0.5, inplace=False)
      (2): Linear(in_features=2048, out_features=4000, bias=True)
    )
    (gating_fc): Sequential(
      (0): BatchNorm1d(2048, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (1): Dropout(p=0.5, inplace=False)
      (2): Linear(in_features=2048, out_features=5, bias=True)
    )
  )
)
[INFO][03/06/2020 12:33:56] SEED: 1635
[INFO][03/06/2020 12:33:56] # of parameters: 32,570,757
[INFO][03/06/2020 12:33:56] # of trainable parameters: 32,570,757
[INFO][03/06/2020 12:33:56] Optimizer Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    eps: 1e-06
    initial_lr: 0.0003
    lr: 0.00029999814373839835
    weight_decay: 0

Parameter Group 1
    amsgrad: False
    betas: (0.9, 0.999)
    eps: 1e-06
    initial_lr: 0.0003
    lr: 0.00029999814373839835
    weight_decay: 0
)
[INFO][03/06/2020 12:33:56] ====================Epoch 1====================
Traceback (most recent call last):
  File "/opt/conda/envs/yt8m/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/envs/yt8m/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/docker/src/yt8m/train_video.py", line 274, in <module>
    main()
  File "/home/docker/src/yt8m/train_video.py", line 265, in main
    train_loader, valid_loader)
  File "/home/docker/src/yt8m/train_video.py", line 182, in train_from_start
    total_steps=n_steps, checkpoint_interval=config['ckpt_interval']
  File "/opt/conda/envs/yt8m/lib/python3.7/site-packages/helperbot/bot.py", line 168, in train
    input_tensors, targets)
  File "/opt/conda/envs/yt8m/lib/python3.7/site-packages/helperbot/bot.py", line 82, in train_one_step
    output = self.model(*input_tensors)
  File "/opt/conda/envs/yt8m/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/docker/src/yt8m/models.py", line 34, in forward
    return self.model(features, masks)
  File "/opt/conda/envs/yt8m/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/docker/src/yt8m/models.py", line 240, in forward
    features[:, :, :self.video_dim], masks)
  File "/opt/conda/envs/yt8m/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/docker/src/yt8m/encoders.py", line 229, in forward
    x = self.expansion_mapper(x)
  File "/opt/conda/envs/yt8m/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/envs/yt8m/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/opt/conda/envs/yt8m/lib/python3.7/site-packages/torch/nn/functional.py", line 1372, in linear
    output = input.matmul(weight.t())
RuntimeError: cannot reshape tensor of 0 elements into shape [-1, 0] because the unspecified dimension size -1 can be any value and is ambiguous
mv: missing destination file operand after 'data/cache/video/nextvlad-2'
Try 'mv --help' for more information.

**Comment by RasmusRavnFrost** [comment]
In case its interesting my conda packages are:

(yt8m) docker@2650d7ddca6f:~/src$ conda list
# packages in environment at /opt/conda/envs/yt8m:
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
absl-py                   0.8.0                    pypi_0    pypi
asn1crypto                0.24.0                   pypi_0    pypi
astor                     0.8.0                    pypi_0    pypi
backcall                  0.1.0                    pypi_0    pypi
blas                      1.0                         mkl  
ca-certificates           2019.5.15                     1  
certifi                   2019.6.16                py37_1  
cffi                      1.12.3           py37h2e261b9_0  
chardet                   3.0.4                    pypi_0    pypi
cryptography              2.7                      pypi_0    pypi
cudatoolkit               10.1.168                      0  
dataclasses               0.6                      pypi_0    pypi
decorator                 4.4.0                    pypi_0    pypi
freetype                  2.9.1                h8a8886c_1  
future                    0.17.1                   pypi_0    pypi
gast                      0.3.1                    pypi_0    pypi
google-pasta              0.1.7                    pypi_0    pypi
grpcio                    1.23.0                   pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
idna                      2.8                      pypi_0    pypi
intel-openmp              2019.4                      243  
ipython                   7.8.0                    pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
jedi                      0.15.1                   pypi_0    pypi
joblib                    0.13.2                   pypi_0    pypi
jpeg                      9b                   h024ee3a_2  
kaggle                    1.5.5                    pypi_0    pypi
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.0                    pypi_0    pypi
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.0.10               h2733197_2  
markdown                  3.1.1                    pypi_0    pypi
mkl                       2019.4                      243  
mkl-service               2.3.0            py37he904b0f_0  
mkl_fft                   1.0.14           py37ha843d7b_0  
mkl_random                1.0.2            py37hd81dba3_0  
ncurses                   6.1                  he6710b0_1  
ninja                     1.9.0            py37hfd86e86_0  
numpy                     1.16.4           py37h7e9f1db_0  
numpy-base                1.16.4           py37hde5b4d6_0  
olefile                   0.46                     py37_0  
openssl                   1.1.1c               h7b6447c_1  
opt-einsum                3.0.1                    pypi_0    pypi
pandas                    0.25.1                   pypi_0    pypi
parso                     0.5.1                    pypi_0    pypi
pexpect                   4.7.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    6.1.0            py37h34e0f95_0  
pip                       19.2.2                   py37_0  
prompt-toolkit            2.0.9                    pypi_0    pypi
protobuf                  3.9.1                    pypi_0    pypi
ptyprocess                0.6.0                    pypi_0    pypi
pycparser                 2.19                     py37_0  
pygments                  2.4.2                    pypi_0    pypi
python                    3.7.4                h265db76_1  
python-dateutil           2.8.0                    pypi_0    pypi
python-slugify            3.0.3                    pypi_0    pypi
python-telegram-bot       12.0.0                   pypi_0    pypi
pytorch                   1.3.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
pytorchhelperbot          0.3.0                    pypi_0    pypi
pytz                      2019.2                   pypi_0    pypi
pyyaml                    5.1.2                    pypi_0    pypi
readline                  7.0                  h7b6447c_5  
requests                  2.22.0                   pypi_0    pypi
scikit-learn              0.21.3                   pypi_0    pypi
scipy                     1.3.1                    pypi_0    pypi
setuptools                41.0.1                   py37_0  
six                       1.12.0                   py37_0  
sqlite                    3.29.0               h7b6447c_0  
tb-nightly                1.15.0a20190806          pypi_0    pypi
tensorboardx              1.8                      pypi_0    pypi
tensorflow                2.0.0rc0                 pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
text-unidecode            1.2                      pypi_0    pypi
tf-estimator-nightly      1.14.0.dev2019080601          pypi_0    pypi
tk                        8.6.8                hbc83047_0  
tornado                   6.0.3                    pypi_0    pypi
tqdm                      4.35.0                   pypi_0    pypi
traitlets                 4.3.2                    pypi_0    pypi
urllib3                   1.24.3                   pypi_0    pypi
wcwidth                   0.1.7                    pypi_0    pypi
werkzeug                  0.15.6                   pypi_0    pypi
wheel                     0.33.4                   py37_0  
wrapt                     1.11.2                   pypi_0    pypi
xz                        5.2.4                h14c3975_4  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.3.7                h0b5b093_0

**Comment by ceshine** [comment]
> RuntimeError: cannot reshape **tensor of 0 elements** into shape [-1, 0] because the unspecified dimension size -1 can be any value and is ambiguous

Looks like the data loader did not load any data into the pipeline. Are you sure you have put all data into their corresponding directories? Because I did reproduce the results using the same public docker image, there's no point comparing Conda packages.

Please first make sure the data loader has something to collect from, i.e., [collect_file_paths](https://github.com/ceshine/yt8m-2019/blob/a18605bbde6f4e0b1ab441121e702db1ee1f38a9/yt8m/train_video.py#L107) actually returns something. Then we can move on to see what's really going on in the data loader.

**Comment by ceshine** [comment]
BTW, I'm almost certain that `tensorflow==2.0.0rc0` was what I used for this project, so I don't think the problem is the version of Tensorflow. Reproducibility is important to me, so I went through all the troubles to create a Docker image and rerun all the steps to reproduce the results. I hope we can figure out what's going on here. I suspect the reason is that I forgot to add or misspecified some arguments in the creation command of the Docker container:

```
docker run --gpus all \
    -v /path/to/segment/dataset:/home/docker/src/data/segment \
    -v /path/to/video/dataset:/home/docker/src/data/video \
    --shm-size=1G -ti --name mycontainer \
    ceshine/yt8m-2019
```

**Comment by ceshine** [comment]
I figured out what went wrong — you were using the wrong data set. The "video dataset" here is the [Frame-level features dataset in the yt8m download page](https://research.google.com/youtube8m/download.html), and you were using the Video-level features dataset. 

It's quite embarrassing that I also downloaded the wrong data set in my first attempt to reproduce your problem. The yt8m download page doesn't have anchor points so I couldn't link directly to the the download instructions for the frame-level data set. I'll add a warning to README and hopefully it'll prevent people from making the same mistake.

To reiterate, my diagnosis is that you downloaded the "video dataset" using this command:

```
curl data.yt8m.org/download.py | partition=2/video/train mirror=us python 
```

But the correct one is actually:

```
curl data.yt8m.org/download.py | partition=2/frame/train mirror=us python 
```

Please let me know if you encounter any further problems.

**Comment by RasmusRavnFrost** [comment]
Hi. Yes, you are correct I have the wrong files (a little bit embarrassing for me too :) ). I am currently downloading the correct ones and expect it will work. 
One thing confuses me though.
 I do have a question: From the download page: https://research.google.com/youtube8m/download.html
for the **Segment-rated frame-level features dataset** there is only validation and test data, but in the folder, in your project, it contains a **train** and **test** folder. But since there isn't any training to download am I supposed to use the test data a training data? Or am I missing something? 
Thanks for your thorough and very useful response.

**Comment by ceshine** [comment]
Sorry for the late reply.

Please put the validation data into the **train** folder. Because that's the only labelled data we have, the only way to do supervised learning is to use it as training data (a subset of it will be used as validation data).

Thanks for the question. I'll add a clarification in the README. There seem to be quite a few things that seem obvious to me at that time, but actually confusing to newcomers.

**Comment by RasmusRavnFrost** [comment]
Yeah, that was my conclusion as well but thanks a lot for the confirmation :) 
two minor suggestions to make it more clear for newcomers as well.
Unless I am mistaken the validation data files put into the train folder should be renamed as well right?
Also, you have a minor spelling error in the "bash scripts/pretraning.bash" under Reproduction Instructions (there is missing an "i").

**Comment by ceshine** [comment]
No, you don't have to rename the file inside the train folder. The [glob pattern](https://github.com/ceshine/yt8m-2019/blob/c5b77dee1a2eba7b767879ade9e813c87e526c0b/yt8m/train_pure_segment.py#L109) used is `DATA_DIR_STR + "train/*.tfrecord"`, that is, every .tfrecord file inside the train folder will be collected.

Thanks for pointing out the typo. I'll fix it right away.

**Comment by RasmusRavnFrost** [comment]
Ahh, smart. Thx so much for the awesome support :)

**Comment by ceshine** [comment]
Thanks for your feedback!
