### ISSUE TITLE
whitening

### ISSUE THREAD

**Issue by ibrahimrazu** [ceshine/yt8m-2019#5]
Hi, 
Thanks for sharing your awesome code. I am just curious, did you implement the reverse whitening mentioned in the paper? 

Thanks!

**Comment by ceshine** [comment]
Not sure which paper you're refereing to. My paper does not mention whitening, so I'd guess that it did not get implemented.

**Comment by ibrahimrazu** [comment]
Thanks a lot for your reply. Yes, i also understood later on that whitening was not implemented. however, i have another question. for DBoF and NextVLAD training, you used steps and only one epoch. is that the standard?

**Comment by ceshine** [comment]
I definitely wouldn't call it the standard. It's just a hyper-parameter that I found working well enough given the limited computing resources. You're welcome to try other settings if your hardware configuration is different from mine (e.g., multiple GPUs).

EDIT: grammar

**Comment by ibrahimrazu** [comment]
i see, thanks a lot for your nice repo. it helps me a lot :)

**Comment by ceshine** [comment]
Glad to be of help!
